version: '1'
services:
  frontend:
    container_name: 'frontend-nginx'
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-1

  backend-1:
    container_name: 'load-balancer'
    build: ../shortener
    restart: always
    ports:
      - "1001:80"
    depends_on:
      - redis
      - mysql
    environment:
      - dbHost=127.0.0.1
      - dbUser=root
      - dbPassword=2rjurrru
      - dbName=urlshortener
      - redisConnectionString='redis://localhost:6380'
      - enableRedis=off
  
  cache:
    container_name: 'redis'
    image: redis
    ports:
      - 6380:6380
    
  db:
    container_name: 'mysql'
    image: mysql
    command: --default-authentication-plugin=2rjurrru
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2rjurrru
      MYSQL_DATABASE: urlshortener
    volumes:
      - ./mysql:/docker-entrypoint-initdb.db
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

       